# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue May 28 00:25:33 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Iconos/icons/metodos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(565, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.metodosRaices = QtGui.QComboBox(self.tab)
        self.metodosRaices.setObjectName(_fromUtf8("metodosRaices"))
        self.metodosRaices.addItem(_fromUtf8(""))
        self.metodosRaices.addItem(_fromUtf8(""))
        self.metodosRaices.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.metodosRaices, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Chancery L"))
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 2)
        self.editRaices = QtGui.QLineEdit(self.tab)
        self.editRaices.setObjectName(_fromUtf8("editRaices"))
        self.gridLayout_2.addWidget(self.editRaices, 1, 1, 1, 1)
        self.btnHowFx = QtGui.QPushButton(self.tab)
        self.btnHowFx.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Iconos/icons/what.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHowFx.setIcon(icon1)
        self.btnHowFx.setIconSize(QtCore.QSize(24, 24))
        self.btnHowFx.setObjectName(_fromUtf8("btnHowFx"))
        self.gridLayout_2.addWidget(self.btnHowFx, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.raicesA = QtGui.QLineEdit(self.tab)
        self.raicesA.setObjectName(_fromUtf8("raicesA"))
        self.gridLayout_3.addWidget(self.raicesA, 0, 1, 1, 1)
        self.raicesX = QtGui.QLineEdit(self.tab)
        self.raicesX.setEnabled(False)
        self.raicesX.setObjectName(_fromUtf8("raicesX"))
        self.gridLayout_3.addWidget(self.raicesX, 0, 5, 1, 1)
        self.raicesB = QtGui.QLineEdit(self.tab)
        self.raicesB.setObjectName(_fromUtf8("raicesB"))
        self.gridLayout_3.addWidget(self.raicesB, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 3, 1, 1)
        self.raicesTolera = QtGui.QComboBox(self.tab)
        self.raicesTolera.setObjectName(_fromUtf8("raicesTolera"))
        self.raicesTolera.addItem(_fromUtf8(""))
        self.raicesTolera.addItem(_fromUtf8(""))
        self.raicesTolera.addItem(_fromUtf8(""))
        self.raicesTolera.addItem(_fromUtf8(""))
        self.raicesTolera.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.raicesTolera, 1, 4, 1, 2)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.raicesItera = QtGui.QSpinBox(self.tab)
        self.raicesItera.setObjectName(_fromUtf8("raicesItera"))
        self.gridLayout_3.addWidget(self.raicesItera, 1, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 46, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnRaices = QtGui.QPushButton(self.tab)
        self.btnRaices.setObjectName(_fromUtf8("btnRaices"))
        self.gridLayout_4.addWidget(self.btnRaices, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.metodosMatriz = QtGui.QComboBox(self.tab_2)
        self.metodosMatriz.setObjectName(_fromUtf8("metodosMatriz"))
        self.metodosMatriz.addItem(_fromUtf8(""))
        self.metodosMatriz.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.metodosMatriz, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_6.addWidget(self.label_19, 0, 3, 1, 1)
        self.matrizItera = QtGui.QSpinBox(self.tab_2)
        self.matrizItera.setObjectName(_fromUtf8("matrizItera"))
        self.gridLayout_6.addWidget(self.matrizItera, 0, 4, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.A31 = QtGui.QLineEdit(self.tab_2)
        self.A31.setObjectName(_fromUtf8("A31"))
        self.gridLayout_5.addWidget(self.A31, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.A12 = QtGui.QLineEdit(self.tab_2)
        self.A12.setObjectName(_fromUtf8("A12"))
        self.gridLayout_5.addWidget(self.A12, 1, 2, 1, 1)
        self.A11 = QtGui.QLineEdit(self.tab_2)
        self.A11.setObjectName(_fromUtf8("A11"))
        self.gridLayout_5.addWidget(self.A11, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 0, 1, 1, 1)
        self.A13 = QtGui.QLineEdit(self.tab_2)
        self.A13.setObjectName(_fromUtf8("A13"))
        self.gridLayout_5.addWidget(self.A13, 1, 3, 1, 1)
        self.B1 = QtGui.QLineEdit(self.tab_2)
        self.B1.setObjectName(_fromUtf8("B1"))
        self.gridLayout_5.addWidget(self.B1, 1, 5, 1, 1)
        self.A21 = QtGui.QLineEdit(self.tab_2)
        self.A21.setObjectName(_fromUtf8("A21"))
        self.gridLayout_5.addWidget(self.A21, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 0, 3, 1, 1)
        self.A22 = QtGui.QLineEdit(self.tab_2)
        self.A22.setObjectName(_fromUtf8("A22"))
        self.gridLayout_5.addWidget(self.A22, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.B3 = QtGui.QLineEdit(self.tab_2)
        self.B3.setObjectName(_fromUtf8("B3"))
        self.gridLayout_5.addWidget(self.B3, 3, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 0, 2, 1, 1)
        self.B2 = QtGui.QLineEdit(self.tab_2)
        self.B2.setObjectName(_fromUtf8("B2"))
        self.gridLayout_5.addWidget(self.B2, 2, 5, 1, 1)
        self.A33 = QtGui.QLineEdit(self.tab_2)
        self.A33.setObjectName(_fromUtf8("A33"))
        self.gridLayout_5.addWidget(self.A33, 3, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.A23 = QtGui.QLineEdit(self.tab_2)
        self.A23.setObjectName(_fromUtf8("A23"))
        self.gridLayout_5.addWidget(self.A23, 2, 3, 1, 1)
        self.A32 = QtGui.QLineEdit(self.tab_2)
        self.A32.setObjectName(_fromUtf8("A32"))
        self.gridLayout_5.addWidget(self.A32, 3, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        spacerItem4 = QtGui.QSpacerItem(20, 43, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.btnMatriz = QtGui.QPushButton(self.tab_2)
        self.btnMatriz.setObjectName(_fromUtf8("btnMatriz"))
        self.verticalLayout_3.addWidget(self.btnMatriz)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_20 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_4.addWidget(self.label_20)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setPixmap(QtGui.QPixmap(_fromUtf8(":/Imagenes/images/formula.png")))
        self.label_21.setScaledContents(False)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_7)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 0, 0, 1, 1)
        self.metodosIntegral = QtGui.QComboBox(self.tab_3)
        self.metodosIntegral.setObjectName(_fromUtf8("metodosIntegral"))
        self.metodosIntegral.addItem(_fromUtf8(""))
        self.metodosIntegral.addItem(_fromUtf8(""))
        self.metodosIntegral.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.metodosIntegral, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Chancery L"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 1, 0, 1, 1)
        self.fxIntegral = QtGui.QLineEdit(self.tab_3)
        self.fxIntegral.setObjectName(_fromUtf8("fxIntegral"))
        self.gridLayout_8.addWidget(self.fxIntegral, 1, 1, 1, 1)
        self.btnHowFx2 = QtGui.QPushButton(self.tab_3)
        self.btnHowFx2.setText(_fromUtf8(""))
        self.btnHowFx2.setIcon(icon1)
        self.btnHowFx2.setIconSize(QtCore.QSize(24, 24))
        self.btnHowFx2.setObjectName(_fromUtf8("btnHowFx2"))
        self.gridLayout_8.addWidget(self.btnHowFx2, 1, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 2, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_4.addWidget(self.line_3)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.bIntegral = QtGui.QLineEdit(self.tab_3)
        self.bIntegral.setObjectName(_fromUtf8("bIntegral"))
        self.gridLayout_9.addWidget(self.bIntegral, 0, 4, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_9.addWidget(self.label_26, 1, 0, 1, 1)
        self.integralItera = QtGui.QSpinBox(self.tab_3)
        self.integralItera.setObjectName(_fromUtf8("integralItera"))
        self.gridLayout_9.addWidget(self.integralItera, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_9.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 0, 3, 1, 1)
        self.aIntegral = QtGui.QLineEdit(self.tab_3)
        self.aIntegral.setObjectName(_fromUtf8("aIntegral"))
        self.gridLayout_9.addWidget(self.aIntegral, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 0, 5, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 1, 3, 1, 3)
        self.verticalLayout_4.addLayout(self.gridLayout_9)
        spacerItem11 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.btnIntegral = QtGui.QPushButton(self.tab_3)
        self.btnIntegral.setObjectName(_fromUtf8("btnIntegral"))
        self.verticalLayout_4.addWidget(self.btnIntegral)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_27 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_5.addWidget(self.label_27)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.yPrima = QtGui.QLineEdit(self.tab_4)
        self.yPrima.setObjectName(_fromUtf8("yPrima"))
        self.gridLayout_10.addWidget(self.yPrima, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Chancery L"))
        font.setPointSize(13)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_10.addWidget(self.label_29, 1, 0, 1, 1)
        self.metodosEcuaciones = QtGui.QComboBox(self.tab_4)
        self.metodosEcuaciones.setObjectName(_fromUtf8("metodosEcuaciones"))
        self.metodosEcuaciones.addItem(_fromUtf8(""))
        self.metodosEcuaciones.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.metodosEcuaciones, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_10.addWidget(self.label_28, 0, 0, 1, 1)
        self.btnHowFx3 = QtGui.QPushButton(self.tab_4)
        self.btnHowFx3.setText(_fromUtf8(""))
        self.btnHowFx3.setIcon(icon1)
        self.btnHowFx3.setIconSize(QtCore.QSize(24, 24))
        self.btnHowFx3.setObjectName(_fromUtf8("btnHowFx3"))
        self.gridLayout_10.addWidget(self.btnHowFx3, 1, 3, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem12, 0, 2, 1, 2)
        self.verticalLayout_5.addLayout(self.gridLayout_10)
        self.line_4 = QtGui.QFrame(self.tab_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_5.addWidget(self.line_4)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_11.addWidget(self.label_30, 0, 0, 1, 1)
        self.ecuacionesY0 = QtGui.QLineEdit(self.tab_4)
        self.ecuacionesY0.setObjectName(_fromUtf8("ecuacionesY0"))
        self.gridLayout_11.addWidget(self.ecuacionesY0, 0, 5, 1, 1)
        self.ecuacionesX0 = QtGui.QLineEdit(self.tab_4)
        self.ecuacionesX0.setObjectName(_fromUtf8("ecuacionesX0"))
        self.gridLayout_11.addWidget(self.ecuacionesX0, 0, 1, 1, 1)
        self.ecuacionesXn = QtGui.QLineEdit(self.tab_4)
        self.ecuacionesXn.setObjectName(_fromUtf8("ecuacionesXn"))
        self.gridLayout_11.addWidget(self.ecuacionesXn, 0, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_11.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_11.addWidget(self.label_31, 0, 4, 1, 1)
        self.ecuacionesItera = QtGui.QSpinBox(self.tab_4)
        self.ecuacionesItera.setObjectName(_fromUtf8("ecuacionesItera"))
        self.gridLayout_11.addWidget(self.ecuacionesItera, 1, 5, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_4)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_11.addWidget(self.label_33, 1, 3, 1, 2)
        self.verticalLayout_5.addLayout(self.gridLayout_11)
        spacerItem13 = QtGui.QSpacerItem(20, 69, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.btnEcuaciones = QtGui.QPushButton(self.tab_4)
        self.btnEcuaciones.setObjectName(_fromUtf8("btnEcuaciones"))
        self.verticalLayout_5.addWidget(self.btnEcuaciones)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnAcerca = QtGui.QPushButton(self.centralwidget)
        self.btnAcerca.setObjectName(_fromUtf8("btnAcerca"))
        self.gridLayout.addWidget(self.btnAcerca, 0, 0, 1, 1)
        self.btnSalir = QtGui.QPushButton(self.centralwidget)
        self.btnSalir.setObjectName(_fromUtf8("btnSalir"))
        self.gridLayout.addWidget(self.btnSalir, 0, 2, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.btnSalir, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.metodosRaices)
        MainWindow.setTabOrder(self.metodosRaices, self.editRaices)
        MainWindow.setTabOrder(self.editRaices, self.raicesA)
        MainWindow.setTabOrder(self.raicesA, self.raicesB)
        MainWindow.setTabOrder(self.raicesB, self.raicesX)
        MainWindow.setTabOrder(self.raicesX, self.raicesItera)
        MainWindow.setTabOrder(self.raicesItera, self.raicesTolera)
        MainWindow.setTabOrder(self.raicesTolera, self.btnRaices)
        MainWindow.setTabOrder(self.btnRaices, self.metodosMatriz)
        MainWindow.setTabOrder(self.metodosMatriz, self.matrizItera)
        MainWindow.setTabOrder(self.matrizItera, self.A11)
        MainWindow.setTabOrder(self.A11, self.A12)
        MainWindow.setTabOrder(self.A12, self.A13)
        MainWindow.setTabOrder(self.A13, self.B1)
        MainWindow.setTabOrder(self.B1, self.A21)
        MainWindow.setTabOrder(self.A21, self.A22)
        MainWindow.setTabOrder(self.A22, self.A23)
        MainWindow.setTabOrder(self.A23, self.B2)
        MainWindow.setTabOrder(self.B2, self.A31)
        MainWindow.setTabOrder(self.A31, self.A32)
        MainWindow.setTabOrder(self.A32, self.A33)
        MainWindow.setTabOrder(self.A33, self.B3)
        MainWindow.setTabOrder(self.B3, self.btnMatriz)
        MainWindow.setTabOrder(self.btnMatriz, self.metodosIntegral)
        MainWindow.setTabOrder(self.metodosIntegral, self.fxIntegral)
        MainWindow.setTabOrder(self.fxIntegral, self.aIntegral)
        MainWindow.setTabOrder(self.aIntegral, self.bIntegral)
        MainWindow.setTabOrder(self.bIntegral, self.integralItera)
        MainWindow.setTabOrder(self.integralItera, self.btnIntegral)
        MainWindow.setTabOrder(self.btnIntegral, self.btnSalir)
        MainWindow.setTabOrder(self.btnSalir, self.btnAcerca)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Métodos Numéricos", None))
        self.label.setText(_translate("MainWindow", "Selecciona el tipo de método numérico que deseas aplicar:", None))
        self.label_2.setText(_translate("MainWindow", "Selecciona el método a utilizar e ingresa la función de la cual deseas obtener la raíz:", None))
        self.metodosRaices.setItemText(0, _translate("MainWindow", "Método de Bisección", None))
        self.metodosRaices.setItemText(1, _translate("MainWindow", "Método de la Regla Falsa", None))
        self.metodosRaices.setItemText(2, _translate("MainWindow", "Método de Newton - Raphson", None))
        self.label_3.setText(_translate("MainWindow", "Método a utilizar: ", None))
        self.label_4.setText(_translate("MainWindow", "f(x) = ", None))
        self.btnHowFx.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.label_5.setText(_translate("MainWindow", "Determina los valores que te son solicitados:", None))
        self.label_6.setText(_translate("MainWindow", "Extremo A: ", None))
        self.label_7.setText(_translate("MainWindow", "Extremo B: ", None))
        self.label_8.setText(_translate("MainWindow", "Punto X₀: ", None))
        self.label_10.setText(_translate("MainWindow", "Tolerancia:", None))
        self.raicesTolera.setItemText(0, _translate("MainWindow", "0.001", None))
        self.raicesTolera.setItemText(1, _translate("MainWindow", "0.0001", None))
        self.raicesTolera.setItemText(2, _translate("MainWindow", "0.00001", None))
        self.raicesTolera.setItemText(3, _translate("MainWindow", "0.000001", None))
        self.raicesTolera.setItemText(4, _translate("MainWindow", "0.0000001", None))
        self.label_9.setText(_translate("MainWindow", "N° Iteraciones:", None))
        self.btnRaices.setText(_translate("MainWindow", "Calcular la aproximaxión", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Aprox. de Raíces", None))
        self.label_11.setText(_translate("MainWindow", "Selecciona el método a utilizar y proporciona los coeficientes de cada ecuación, recuerda que deben encontrarse en diagonal fuerte:", None))
        self.metodosMatriz.setItemText(0, _translate("MainWindow", "Método de Jacobi", None))
        self.metodosMatriz.setItemText(1, _translate("MainWindow", "Método de Gauss - Seidel", None))
        self.label_19.setText(_translate("MainWindow", "Iteraciones a realizar: ", None))
        self.label_18.setText(_translate("MainWindow", "Método a utilizar: ", None))
        self.label_14.setText(_translate("MainWindow", "EQ₃", None))
        self.label_15.setText(_translate("MainWindow", "X₁", None))
        self.label_17.setText(_translate("MainWindow", "X₃", None))
        self.label_13.setText(_translate("MainWindow", "EQ₂", None))
        self.label_16.setText(_translate("MainWindow", "X₂", None))
        self.label_12.setText(_translate("MainWindow", "EQ₁", None))
        self.btnMatriz.setText(_translate("MainWindow", "Calcular los valores de X", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sist. de Ecuaciones", None))
        self.label_20.setText(_translate("MainWindow", "Selecciona el método a utilizar e ingresa los datos que se solicitan en base a la siguiente estructura:", None))
        self.label_22.setText(_translate("MainWindow", "Método a utilizar: ", None))
        self.metodosIntegral.setItemText(0, _translate("MainWindow", "Sumas de Riemann", None))
        self.metodosIntegral.setItemText(1, _translate("MainWindow", "Regla del Trapecio", None))
        self.metodosIntegral.setItemText(2, _translate("MainWindow", "Regla de Simpson ⅓", None))
        self.label_23.setText(_translate("MainWindow", "f(x) : ", None))
        self.label_26.setText(_translate("MainWindow", "Iteraciones a realizar:", None))
        self.label_24.setText(_translate("MainWindow", "Valor de A: ", None))
        self.label_25.setText(_translate("MainWindow", "Valor de B: ", None))
        self.btnIntegral.setText(_translate("MainWindow", "Calcular la estimación de la Integral", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Integración Numérica", None))
        self.label_27.setText(_translate("MainWindow", "Selecciona el método a utilizar e ingresa la ecuación diferencial que deseas resolver:", None))
        self.label_29.setText(_translate("MainWindow", "y\' = ", None))
        self.metodosEcuaciones.setItemText(0, _translate("MainWindow", "Método de Euler", None))
        self.metodosEcuaciones.setItemText(1, _translate("MainWindow", "Método RK-4", None))
        self.label_28.setText(_translate("MainWindow", "Método a utilizar:", None))
        self.label_30.setText(_translate("MainWindow", "X₀: ", None))
        self.label_32.setText(_translate("MainWindow", "Xₙ: ", None))
        self.label_31.setText(_translate("MainWindow", "Y₀: ", None))
        self.label_33.setText(_translate("MainWindow", "Iteraciones a realizar: ", None))
        self.btnEcuaciones.setText(_translate("MainWindow", "Calcular la aproximación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Ecuaciones Diferenciales", None))
        self.btnAcerca.setText(_translate("MainWindow", "Acerca de", None))
        self.btnSalir.setText(_translate("MainWindow", "Salir", None))

import metnum_rc
